### PR TITLE
First pass at Modules template

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by mmun** [comment]
LGTM

**Comment by rwjblue** [comment]
@samselikoff - Can you link a screenshot? I haven't had a chance to pull it down locally and test, but the changes look good.

**Comment by samselikoff** [comment]
image

**Comment by samselikoff** [comment]
image

**Comment by samselikoff** [comment]
image

**Comment by samselikoff** [comment]
Ok, I addressed @mmun's comments

**Comment by rwjblue** [comment]
@samselikoff - Thank you.

**Comment by samselikoff** [comment]
\o/ first major open source commit for me!

**Comment by rwjblue** [comment]
@samselikoff -  :beers: Welcome to the club! (be careful its addicting)

**Pull request merged**
